name: ci pipeline

on:
  push:
    branches: [ main, mya ]
  pull_request:
    branches: [ main, mya ]

env:
  GO_VERSION: 1.21

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum  

      - name: Clean workspace
        run: |
          go clean -modcache 2>/dev/null || true
          rm -f go.sum

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run tests
        run: make test
